export const depara = {
  cid: "client_id",
  cm: "campaign_medium",
  cs: "campaign_source",
  ni: "non_interaction",
  ul: "user_language",
  v: "ga_version",
  ht: "hit_time",
  aid: "app_id",
  aiid: "app_installer_id",
  an: "app_name",
  av: "app_version",
  cd: "screen_name",
  ec: "event_category",
  ea: "event_action",
  el: "event_label",
  t: "hit_type",
  tid: "property_id",
  promoa: "promotion_action",
  pa: "product_action",
};

export const product_depara = {
  br: "brand",
  ca: "category",
  id: "id",
  nm: "name",
  pr: "price",
  qt: "quantity",
  cr: "creative",
  ps: "position",
}